name: Build

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build Electron App on ${{ matrix.os }} ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
                arch: [x64, arm64]

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: yarn install

            - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
              run: |
                if ($env:RUNNER_OS -eq 'MacOS') {
                  yarn electron-builder --macos --${{ matrix.arch }}
                } elseif ($env:RUNNER_OS -eq 'Linux') {
                  yarn electron-builder --linux --${{ matrix.arch }}
                } elseif ($env:RUNNER_OS -eq 'Windows') {
                  yarn electron-builder --windows --${{ matrix.arch }}
                }
              shell: pwsh
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Upload Artifacts for ${{ matrix.os }} ${{ matrix.arch }}
              uses: actions/upload-artifact@v3
              with:
                  name: gamepad-io-${{ matrix.os }}-${{ matrix.arch }}
                  path: |
                      dist/**/*
